### ISSUE TITLE
Add a GUI option for Scribblzz mode

### ISSUE THREAD

**Issue by raineycat** [sbcomputertech/redchallenges#1]

**Comment by raineycat** [comment]
There's a weird gui/layout bug where the button doesn't show. Working on it

**Comment by Ecorous** [comment]
wasn't this fixed in fb0a44050d2228b642a95570f5a574d7d4f7cac8?

**Comment by raineycat** [comment]
that commit was after that comment

**Comment by Ecorous** [comment]
Was mainly just poking you ^^
